[package]
name = "soroban_error_buggy"
version = "0.0.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace=true }

[dev_dependencies]
soroban-sdk = { workspace=true, features = ["testutils"] }